### ISSUE TITLE
Integrate Framer-motion to animate the website-landing in desktop view

### ISSUE THREAD

**Issue by pooranjoyb** [sristy17/MindDrive#1]
Use Framer-Motion to animate the website landing page :)

**Comment by 1-SubhamSingh** [comment]
Can you describe what type of animation you want , I mean fading and loading or pop-up from left etc.

**Comment by sristy17** [comment]
> Can you describe what type of animation you want , I mean fading and loading or pop-up from left etc.

Whatever suits the best or that looks good will work :) make sure you add video with the pr, the changes you made!

**Comment by mahenoorsalat** [comment]
let me try to do animation .. if you want then assign me this issue .. Thank you :)

**Comment by mahenoorsalat** [comment]
@sristy17  @pooranjoyb 

> let me try to do animation .. if you want then assign me this issue .. Thank you :)

**Comment by pooranjoyb** [comment]
complete previous issue before starting this 👍🏼 @mahenoorsalat

**Comment by mahenoorsalat** [comment]
yeah I'm working on that only :) @pooranjoyb

**Comment by ipoornima1125** [comment]
@pooranjoyb can i work on this issue?

**Comment by sristy17** [comment]
@mahenoorsalat Are you working on it?

**Comment by nikkvijay** [comment]
I want to work on this issue , can you please assign me.

**Comment by mahenoorsalat** [comment]
> @mahenoorsalat Are you working on it?

Yeah I'm working on it @sristy17 👍
