### ISSUE TITLE
Fix Typo in CONTRIUBINT.md file

### ISSUE THREAD

**Issue by Devanshukoli** [sristy17/MindDrive#10]
So, As you can see in SC here. In *Contributing Rules* section, There is typo in first rule...

![image](https://github.com/user-attachments/assets/8403216d-2ccb-4d7b-9a95-d7af00619b9d)

**Comment by sristy17** [comment]
Make some more changes then will merge! by EOD

**Comment by Devanshukoli** [comment]
Ok. will go through about docs and look out any other things as well. 👍

**Comment by oluwafemioluwatuyi** [comment]
Assign this to me.
