### ISSUE TITLE
Redesign the Navbar.

### ISSUE THREAD

**Issue by HeatBlastee** [sristy17/MindDrive#13]
We can redesign the navbar like adding proper privacy page link and terms and condition. Like giving it proper section.

**Comment by HeatBlastee** [comment]
@sristy17 please assign me under hactoberfest

**Comment by sristy17** [comment]
> We can redesign the navbar like adding proper privacy page link and terms and condition. Like giving it proper section.

Yeah sure

**Comment by oluwafemioluwatuyi** [comment]
Is there anything feature to work on

**Comment by sristy17** [comment]
> Is there anything feature to work on

You can check and raise issue based on it, if you find any relevant that can be added!
