### ISSUE TITLE
[FEATURE] Add commitizen in the Project

### ISSUE THREAD

**Issue by Devanshukoli** [sristy17/MindDrive#14]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Yes, My Feature request is related to an *unavailable* functionality in the project. And I would like to add it.

### Proposed Solution

So basically **Commitizen** is GitHub cli tool that helps when commit. And It's very easy to use by just typing `git cz` in terminal  and then can accessible.
Here are it's official [doc](https://github.com/commitizen/cz-cli)

### Screenshots

[Demo Link](https://drive.google.com/file/d/138EVcXvtSQ2trT73wpzTsdz3dGB2Y-k6/view?usp=sharing)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I have add a video demo link on how this works. And I think it is very easy to use and beginner friendly as well. Which is daily developer routine as well.

**Comment by sristy17** [comment]
Sounds cool! Can give a try. @Devanshukoli
