### ISSUE TITLE
github and support buttons are invisible non-responsive to hover

### ISSUE THREAD

**Issue by Speedysays01** [sristy17/MindDrive#15]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Live website

### Version of website/mobile (for example "v1.2.3")

.

### Description

The buttons navigating to github and 'support us' are not clearly visible due to white border and are not responsive to hover or click actions. 

### Steps to Reproduce

Found the issue on the landing page of the site and fixing this can make an improvement in the UI

### Screenshots

![Screenshot 2024-10-01 190624](https://github.com/user-attachments/assets/60226194-82a5-4837-bcf5-7eb7ce01b63b)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

Please assign me this issue under Hacktoberfest and I'll improve the UI of the buttons as well as make them react to hover and click!

**Comment by sristy17** [comment]
> ### Has this bug been raised before?
> * [x]  I have checked "open" AND "closed" issues and this is not a duplicate
> 
> ### Where did you find this bug?
> Live website
> 
> ### Version of website/mobile (for example "v1.2.3")
> .
> 
> ### Description
> The buttons navigating to github and 'support us' are not clearly visible due to white border and are not responsive to hover or click actions.
> 
> ### Steps to Reproduce
> Found the issue on the landing page of the site and fixing this can make an improvement in the UI
> 
> ### Screenshots
> ![Screenshot 2024-10-01 190624](https://private-user-images.githubusercontent.com/150716736/372490550-60226194-82a5-4837-bcf5-7eb7ce01b63b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3OTQ0NzMsIm5iZiI6MTcyNzc5NDE3MywicGF0aCI6Ii8xNTA3MTY3MzYvMzcyNDkwNTUwLTYwMjI2MTk0LTgyYTUtNDgzNy1iY2Y1LTdlYjdjZTAxYjYzYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQxNDQ5MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjYyOTlhMGUxZWM2OTE2NjU5MmU0NTMxNGRjZDhhNTk1NzliNDkyN2VmNjEzYWQwNjM1ZjZmZDk1NGYxMmYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.u8welyRJVEzY8aX_JVOlnJ7V05xxwxmlZ-SJnGY5w-Q)
> 
> ### Do you want to work on this issue?
> Yes
> 
> ### If "yes" to above, please explain how you would technically implement this
> Please assign me this issue under Hacktoberfest and I'll improve the UI of the buttons as well as make them react to hover and click!

This ia a PWA, so this wont view in mobile version. This landing page in only for desktop version.

**Comment by Speedysays01** [comment]
I could resolve the issue for the laptop version then!

**Comment by sristy17** [comment]
> I could resolve the issue for the laptop version then!


Issue as if? Hover and border Issue?

**Comment by Speedysays01** [comment]
Yes. And if there are any more UI Requirements I can do those too. Just let me know

**Comment by pooranjoyb** [comment]
> Yes. And if there are any more UI Requirements I can do those too. Just let me know

Hii @Speedysays01 you can work on other issues I'd say coz, this as this is a PWA so are mostly focused on the Mobile Version rather that adding responsiveness to the Desktop Version.

Hope you understand. Happy Coding :)

**Comment by Speedysays01** [comment]
Would check out the mobile version then!
