### ISSUE TITLE
Generate default messages using Github Actions.

### ISSUE THREAD

**Issue by sristy17** [sristy17/MindDrive#16]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

-Generate default (eg. welcome messages) messages when user create a PR or Issues, when PR is merged or Isuue is closed using Github actions.

### Proposed Solution

 Use Github actions.

### Do you want to work on this issue?

No

**Comment by Swayam-hue** [comment]
Assign me this issue.

**Comment by sristy17** [comment]
@Swayam-hue Go for it! :)
