### ISSUE TITLE
Update the Readme File

### ISSUE THREAD

**Issue by sristy17** [sristy17/MindDrive#17]
-Update the folder structure in the Readme file.
- Add contributors list in the Readme Files.

**Comment by pchy-ynda** [comment]
Hello, I'd like to work on this task, Can you please assign it to me?

**Comment by pooranjoyb** [comment]
Go ahead @pchy-ynda

**Comment by pchy-ynda** [comment]
Thanks, but I do need access to the contributors list first. I'll DM @sristy17  on Discord.
