### ISSUE TITLE
[FEATURE] Fixing a part of the hero section

### ISSUE THREAD

**Issue by ayush-848** [sristy17/MindDrive#18]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

![image](https://github.com/user-attachments/assets/b549bd79-53f0-4fa0-9e72-4b0eb94c7f92)

### Proposed Solution

I will regroup the words in a more proper way and up style the buttons 

### Do you want to work on this issue?

No

**Comment by ayush-848** [comment]
Please assign this issue to me

**Comment by pooranjoyb** [comment]
Refer [here](https://github.com/sristy17/MindDrive/issues/15#issuecomment-2386428782) @ayush-848
