### ISSUE TITLE
[Scroll-up for mobile version with animations] 

### ISSUE THREAD

**Issue by Swayam-hue** [sristy17/MindDrive#19]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

No button to directly scroll up to the top of the page in one go.

### Proposed Solution

A simple button with basic HTML/CSS/JS implementation.

### Do you want to work on this issue?

Yes

**Comment by sristy17** [comment]
@Swayam-hue  Go fot it!
