### ISSUE TITLE
User Authentication (Signup)

### ISSUE THREAD

**Issue by pooranjoyb** [sristy17/MindDrive#3]
- Use the `collection.json` from Release and import it to your Postman.
- Use the predefined routes to test the APIs
- Integrate the Signup feature

**Comment by theCodeCrusaderX** [comment]
please assign this issue to me

**Comment by pooranjoyb** [comment]
Go ahead :) @theCodeCrusaderX

**Comment by theCodeCrusaderX** [comment]
please provide collection.json file , i can not found

**Comment by sristy17** [comment]
> please provide collection.json file , i can not found

Check the release notes
