### ISSUE TITLE
 The footer styling is inconsistent across different pages when viewed on mobile devices. 

### ISSUE THREAD

**Issue by manthanmk66** [sristy17/MindDrive#31]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

live website

### Version of website/mobile (for example "v1.2.3")

v0.0.1

### Description

 The footer styling is inconsistent across different pages when viewed on mobile devices. Some pages have different margins, padding, font sizes, or alignment in the footer compared to others. This inconsistency affects the user experience, as the footer does not maintain a uniform appearance throughout the application.

### Steps to Reproduce

Page: Different pages (Mobile view).
Action: Viewed the footer in mobile view.
Problem: Footer styling varies across pages, causing inconsistency in alignment, padding, or font size.

This is a bug affecting the design consistency on mobile devices.

### Screenshots

![image](https://github.com/user-attachments/assets/b086033b-bf1e-4adc-8d54-4f5ec32349cb)

![image](https://github.com/user-attachments/assets/ce2321e3-d26d-46fe-8e2f-0c69f935c590)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I will check for the same styling for all pages

**Comment by pooranjoyb** [comment]
Yep you can fix this :) @manthanmk66
