### ISSUE TITLE
[FEATURE] Auth Management

### ISSUE THREAD

**Issue by pooranjoyb** [sristy17/MindDrive#33]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Tasks : 

- As of now, after the logins, or signups, nothing happens, just the success/failure response.

### Proposed Solution

- So, on successful Login, save the Auth Data to localstorage with the key "authData" and navigate the user to Home Page 
- Create a Logout button in the top-right corner of the Navbar in PWA to Logout the user
- Clear the local storage on Logout.

### Screenshots

Use this Logout button,

https://icons.getbootstrap.com/icons/box-arrow-left/

### Do you want to work on this issue?

No

**Comment by theCodeCrusaderX** [comment]
i can work on this .
i will be using jwt to generate access token and save it on cookies as well as localStorage 

in backend i have to add some routes like for logout and some controllers having all the things that is required .

can you assign me this issue??

**Comment by pooranjoyb** [comment]
> i can work on this . i will be using jwt to generate access token and save it on cookies as well as localStorage
> 
Doing both jwt based auth and again saving cookies for session based doesnot seem right. I guess it will be better if we do either token or session. your views on this? @sristy17 

also i don't think we need to create an extra route for logout, we can just clear the session/token to achieve Logout.

**Comment by pooranjoyb** [comment]
> > i can work on this . i will be using jwt to generate access token and save it on cookies as well as localStorage
> 
> Doing both jwt based auth and again saving cookies for session based doesnot seem right. I guess it will be better if we do either token or session. your views on this? @sristy17

also i don't think we need to create an extra route for logout, we can just clear the session/token to achieve Logout.

**Comment by theCodeCrusaderX** [comment]
no no i was telling you that using jwt i can create the token, and that token i can store it in browser cookies and once token is stored in cookies than for further use we can store in localStorage.

and if you dont want to create me a extra route for logout no problem i will handel this on frontend by removing token in localStorage 

this is what i will be doing:-

1. After login/signup: Store the JWT in localStorage and navigate the user to the Home Page.
2. Logout: Add a button to clear localStorage and redirect the user to the login page.

**Comment by pooranjoyb** [comment]
Okay so basically the token based Authentication. Please don't forget to clear the data while logging out.
I wanted session based authentication tbh, but token will also do. Go ahead with jwt then. all the best. @theCodeCrusaderX

**Comment by theCodeCrusaderX** [comment]
please all mongo connection network to 0.0.0.0

i am facing this issue 

![image](https://github.com/user-attachments/assets/3fff22fa-1395-441f-aedb-e2b604692cd6)

**Comment by pooranjoyb** [comment]
> please all mongo connection network to 0.0.0.0
> 
> i am facing this issue 

It's already set to 0.0.0.0. Please check the creds and env vars.
