### ISSUE TITLE
SEO Enhancement

### ISSUE THREAD

**Issue by mahenoorsalat** [sristy17/MindDrive#35]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

As an SEO expert, I’ve noticed that our current website lacks structured data markup, which is crucial for search engines to understand our content better. This absence limits our visibility and ranking potential. For example, I’m always frustrated when our pages do not appear in rich snippets, which could significantly enhance our click-through rates.

### Proposed Solution

**I propose enhancing our website's SEO by optimizing the following:**

Meta Tags:

- Ensure each page has unique and relevant title tags and meta descriptions that accurately describe the content. This will help improve click-through rates from search engine results.

- Utilize relevant keywords naturally within the title and description, keeping within character limits (approximately 60 characters for titles and 155 characters for descriptions).

- Ensure that alt text is relevant, concise, and descriptive, ideally incorporating target keywords without keyword stuffing.

### Do you want to work on this issue?

No

### If "yes" to above, please explain how you would technically implement this

**Our current meta tags and image alt attributes to identify areas for improvement.** 

**The implementation process will include:**

- Updating the HTML files of each page to incorporate optimized meta tags.

- Reviewing each image to ensure alt attributes are added and optimized.

- Monitoring the website's performance using tools like Google Search Console to analyze the impact of these enhancements on our SEO rankings.

Ping @sristy17

**Comment by Devanshukoli** [comment]
That's cool! I also like to see that as well. :)

**Comment by mahenoorsalat** [comment]
Hello @pooranjoyb @sristy17 ,

I wanted to inform you that I have successfully pushed the changes related to the "SEO Enhancement #35" issue. Please take a moment to review the modifications at your convenience.
