### ISSUE TITLE
User Authentication (Profile)

### ISSUE THREAD

**Issue by pooranjoyb** [sristy17/MindDrive#4]
- Use the collection.json from Release and import it to your Postman.
- Use the predefined routes to test the APIs
- Integrate the Profile feature

**Comment by theCodeCrusaderX** [comment]
please assign this issue to me

**Comment by pooranjoyb** [comment]
2 issues at a time please. @theCodeCrusaderX

**Comment by smritidoneria** [comment]
hey, I want to work upon this issue

**Comment by sristy17** [comment]
@smritidoneria Go for it!

**Comment by AratiAmbekar** [comment]
Please assign this issue to me.

**Comment by pooranjoyb** [comment]
You can work on this now. @AratiAmbekar
