### ISSUE TITLE
Remove Background from Emojis for Better Compatibility with Dark Mode.

### ISSUE THREAD

**Issue by mahenoorsalat** [sristy17/MindDrive#40]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

- When the site is switched to dark mode, the emojis appear with a background that does not blend well with the black color, causing a visual inconsistency. This affects the overall user experience, making the emojis look out of place.

### Proposed Solution

- Remove the background of the emojis, so they blend seamlessly with both light and dark modes. A transparent background for emojis will ensure they look good regardless of the theme. You can refer to how other websites handle emoji transparency in different color schemes for better compatibility.

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

- I plan to remove the emoji backgrounds by adjusting the CSS or replacing the emoji images with transparent versions. I will test the implementation to ensure proper rendering in both light and dark modes, maintaining visual consistency across the site.

**Please assign me this issue, and I will look into it. I look forward to your response!**

Thank you :)

Ping @sristy17 @pooranjoyb

**Comment by pooranjoyb** [comment]
Go for this. @mahenoorsalat

**Comment by pooranjoyb** [comment]
Add this in #39 itself. We don't need another PR for this minor change @mahenoorsalat

**Comment by mahenoorsalat** [comment]
yeah sure!
