### ISSUE TITLE
[BUG] Add/Design Favicon, Logo...

### ISSUE THREAD

**Issue by Devanshukoli** [sristy17/MindDrive#41]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

In live website

### Version of website/mobile (for example "v1.2.3")

v0.0.1

### Description

So, Hey! I noticed this while browsing the landing page. The website missing it's logo, Favicon to show. And I was wondering if I can make it. 

### Steps to Reproduce

By visiting our website, it can be seen on the **Left-corner** of site name.

### Screenshots

Favicon missing SC...
![image](https://github.com/user-attachments/assets/68d04747-5b2e-4872-8a97-a75223e42fe2)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

Honestly, I haven't created nor do I have any experience in creating *Logo*'s and *Favicon*'s. But I still want to give it a shot. So, Yes I would like to work on it. 😀

CC : @pooranjoyb @sristy17

**Comment by pooranjoyb** [comment]
you can go ahead with these. @Devanshukoli

**Comment by pooranjoyb** [comment]
#39 completed this.

**Comment by Devanshukoli** [comment]
Ok, No worries. 👍
