### ISSUE TITLE
[BUG] Dark Mode - UI bugs

### ISSUE THREAD

**Issue by pooranjoyb** [sristy17/MindDrive#42]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Home Page, Chatbot Page

### Version of website/mobile (for example "v1.2.3")

Mobile

### Description

#

### Steps to Reproduce

#

### Screenshots

![image](https://github.com/user-attachments/assets/1153e746-1152-4807-ab8c-d12fc9b22172)

![image](https://github.com/user-attachments/assets/15b16737-abcd-4115-b3bc-b79241ccc3a4)

![image](https://github.com/user-attachments/assets/872bf969-e6c6-478d-9077-023e543d7b73)

### Do you want to work on this issue?

No

**Comment by mahenoorsalat** [comment]
@pooranjoyb let me solve this issues :)

**Comment by pooranjoyb** [comment]
In dark-mode, chatbot, send button is also not visible, please check that too.

**Comment by mahenoorsalat** [comment]
okay 👍

**Comment by mahenoorsalat** [comment]
I updated it by uncommenting that line @pooranjoyb

**Comment by sristy17** [comment]
> I updated it by uncommenting that line @pooranjoyb

I am not able to see changes in your pr :\  I can still see the bugs moreover the changes u made earlier with the cards and the bg-color of the home page is also changed, please share the ss

**Comment by mahenoorsalat** [comment]
you can see in pr #48 I did it but it required reviewer permission @sristy17

**Comment by sristy17** [comment]
> you can see in pr #48 I did it but it required reviewer permission @sristy17 

Ok will let u know
