### ISSUE TITLE
[FEATURE] Show User Details when session data is not expired (Conditional Rendering)

### ISSUE THREAD

**Issue by pooranjoyb** [sristy17/MindDrive#44]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Currently whenever we click on Profile/Avatar we are again redirected to Auth Page, whether or not we are logged in or not.

This is a serious bug we should take care of.

### Proposed Solution

Tasks : 

- When user logs in, save the user data in local storage
- You can see the session created when the user logs in, with an expiry time/date.
- After redirection to Home Page on Login, If I click the avatar button again, I shouldn't see Auth Screen as I am already logged in.
- Instead we need to show the logged in user details.
- Use Conditional Rendering to show userdata/auth-page. Based on the availability of `session-data` and `user-data`.

### Do you want to work on this issue?

No

**Comment by RonakSurana-2001** [comment]
Can I work on this issue

**Comment by pooranjoyb** [comment]
Go for it. @RonakSurana-2001

**Comment by RonakSurana-2001** [comment]
I have opened a PR #46
Kindly Review it
