### ISSUE TITLE
[BUG] Misalignment of Elements on the Landing Page

### ISSUE THREAD

**Issue by mudassir0002** [sristy17/MindDrive#45]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

This issue was found on the live website.

### Version of website/mobile (for example "v1.2.3")

website

### Description

Here’s how you can write your GitHub issue for alignment problems:

Title: [BUG] Misalignment of Elements on the Landing Page
Description:
Issue: There is a misalignment of elements on the landing page. Specifically, the text and image elements are not properly aligned, which disrupts the overall visual flow and creates a cluttered appearance.
![Screenshot (212)](https://github.com/user-attachments/assets/a0d3f87e-48bb-47da-9a2d-1201720e334d)

### Steps to Reproduce

If you know the steps, follow the below format and provide steps to reproduce

For example:

1. Go to <replace your> page.
1. On top right side, close to the <Account> menu
1. Some menu are not working properly.
1. Continue...

If you don't know exact steps, include any relevant details like:

- What page you were on...
- What you were trying to do...
- What went wrong...

### Screenshots

![Screenshot (212)](https://github.com/user-attachments/assets/0d9faf99-293d-4de0-9437-3572c138978e)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

Yes I would propose fixing this issue by adjusting the CSS for the misaligned section. I will ensure the elements are properly aligned and responsive across different screen sizes.

Request: Kindly assign this issue to me and, if possible, add the Hacktoberfest label so it can count towards the event.

**Comment by pooranjoyb** [comment]
As of now we aren't much concerned about the desktop ui. Please have a look in mobile version and check for bugs :)
Hope you understand. Happy coding. @mudassir0002
