### ISSUE TITLE
[BUG] Background breaks on darkmode toggle

### ISSUE THREAD

**Issue by pooranjoyb** [sristy17/MindDrive#51]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

Background Dark image breaks in the Homepage when the darkmode is toggled.

### Screenshots

![image](https://github.com/user-attachments/assets/af541b53-8eaa-4420-9720-3aea9fb42f64)

### Do you want to work on this issue?

No

**Comment by wildcraft958** [comment]
@pooranjoyb can you assign this to me

**Comment by wildcraft958** [comment]
![image](https://github.com/user-attachments/assets/5cb1e5ce-eb27-4248-929f-9d9937a2562b)
Hope this helps

**Comment by wildcraft958** [comment]
![image](https://github.com/user-attachments/assets/c303047d-84a0-4b52-9184-12add031dc57)
changes  are complete

**Comment by wildcraft958** [comment]
![image (1)](https://github.com/user-attachments/assets/666b0dd8-e66a-4e32-aea9-d4813a321e2c)
i hope this fixes the expected issue
I have also added padding and margin to the cards.
