### ISSUE TITLE
[FEATURE] Error Page Template

### ISSUE THREAD

**Issue by pooranjoyb** [sristy17/MindDrive#53]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

We don't have an Error page for the invalid routes. If we hit an invalid route, no page is rendered. 

![image](https://github.com/user-attachments/assets/dbb55881-035f-4c42-bab5-7abc0bcee9fe)

### Proposed Solution

Reproduce a page similar to the MindDrive theme for the Error Page. 
Put the screenshot of design before implementing the same. Mentors will guide you accordingly.

### Do you want to work on this issue?

No

**Comment by Archi-shaw** [comment]
@pooranjoyb Please Assign this issue to mee.

**Comment by pooranjoyb** [comment]
Update @Archi-shaw

**Comment by Archi-shaw** [comment]
Working, will raise pr by tomorrow.
