### ISSUE TITLE
[FEATURE] Improve Nav Icons

### ISSUE THREAD

**Issue by pooranjoyb** [sristy17/MindDrive#54]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

The current navigation icons are very simple and light. You need to make some modifications on the Nav UI to make it attractive.

### Proposed Solution

- Use some vibrant colors of icons that will make the Navigation really attractive
- The Icons should change based on active window. 
   - When the Home is `Active`, Home Icon in the Navbar should be kinda different than when it is `Not Active`
   - Use bubble-effect on click on the icons in the Nav, to ensure a overwhelming user-experience.

### Screenshots

![image](https://github.com/user-attachments/assets/55c13919-31b1-425c-85ff-b24c28911a6d)

### Do you want to work on this issue?

No

**Comment by Archi-shaw** [comment]
@pooranjoyb Please assign this issue to me.

**Comment by pooranjoyb** [comment]
> @pooranjoyb Please assign this issue to me.

Please finish up the ones assigned.

**Comment by jitendrasuthar1998** [comment]
@pooranjoyb Can you please assign this issue to me?

I have noticed one more issue like theme is not consistent.

When user select a dark theme at home page, and then go to about page, or chat page, that time dark theme is not getting applied there.
