### ISSUE TITLE
[BUG] Hostname Fix

### ISSUE THREAD

**Issue by pooranjoyb** [sristy17/MindDrive#56]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

Keeping the hostname as `localhost` explicitly breaks the deployment API calls.
Remove the hostnames and keep the routes only.

https://github.com/sristy17/MindDrive/blob/accc2bd3bd2c8bf320a7c8e58a2348a8375399c2/public/js/auth.js#L23

https://github.com/sristy17/MindDrive/blob/accc2bd3bd2c8bf320a7c8e58a2348a8375399c2/public/js/auth.js#L67

### Do you want to work on this issue?

No

**Comment by wildcraft958** [comment]
@pooranjoyb please assign this to me

**Comment by pooranjoyb** [comment]
> @pooranjoyb please assign this to me

Please raise PRs for the ones assigned.

**Comment by wildcraft958** [comment]
Already  raised you can check
