### ISSUE TITLE
[BUG] Scroll to Top arrow not visible in dark mode

### ISSUE THREAD

**Issue by abhirajadhikary06** [sristy17/MindDrive#58]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

Scroll to Top arrow in the right corner of the webpage is not visible when toggled to dark mode

### Screenshots

![image](https://github.com/user-attachments/assets/e46d7c23-1afc-4663-a033-850466237bb5)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

Just change the arrow color to white so that it adjusts with the dark mode.

**Comment by pooranjoyb** [comment]
Go ahead @abhirajadhikary06

**Comment by pooranjoyb** [comment]
Update? @abhirajadhikary06

**Comment by abhirajadhikary06** [comment]
Sorry, my PCA where going on.. will do I by tomorrow for sure.!
Thank you!
