### ISSUE TITLE
PR & Issues Template (Github Actions)

### ISSUE THREAD

**Issue by pooranjoyb** [sristy17/MindDrive#6]
Automate PR and Issue creation with the Github Actions.

**Comment by Devanshukoli** [comment]
@pooranjoyb Hi, I want to work on this one. I am looking for the actual opp. for testing my *github actions* skills..

**Comment by sristy17** [comment]
@Devanshukoli Go for it!

**Comment by Devanshukoli** [comment]
Hey! Just checking on here, should I write files in `.md` or go for `.yaml`?

**Comment by Devanshukoli** [comment]
Hey! Just wanted to let you know. Just made PR for this issue. #12  
check it out. And tell me if I'm missing on something here. Or any changes. 😀

**Comment by sristy17** [comment]
> Hey! Just wanted to let you know. Just made PR for this issue. #12 check it out. And tell me if I'm missing on something here. Or any changes. 😀

Works! :)
