### ISSUE TITLE
[BUG] Modals content is not visible properly in dark mode

### ISSUE THREAD

**Issue by jitendrasuthar1998** [sristy17/MindDrive#61]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

The modal content which describes the feeling is not visible properly in dark mode.

### Screenshots

![Screenshot_20241214_015834_Chrome](https://github.com/user-attachments/assets/db593fc5-110b-44b9-b7d6-db102c195f07)
![Screenshot_20241214_015854_Chrome](https://github.com/user-attachments/assets/0d3b298b-6dfc-4f97-8d1f-95926407c008)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I will handle content and background color as per dark mode color scheme.
I can work on it.

**Comment by pooranjoyb** [comment]
Closing as duplicate #57
