### ISSUE TITLE
[FEATURE] Add Margin to the top of home page

### ISSUE THREAD

**Issue by Archi-shaw** [sristy17/MindDrive#63]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

We need to add a top margin to prevent the header from collapsing and ensure a clearer appearance.
![Screenshot 2024-12-14 234116](https://github.com/user-attachments/assets/0cc495db-b24b-4b47-9db0-0b71a2ad7b9b)

@pooranjoyb  Please assign this issue to me .

### Proposed Solution

We propose adding a top margin to the page layout to prevent the header from collapsing with the content below it. This will improve the visual clarity and ensure that the header is distinctly separated from the rest of the page, providing a more organized and aesthetically pleasing layout.

### Do you want to work on this issue?

Yes

**Comment by pooranjoyb** [comment]
Could be screen issue. Works fine in my device ://
