### ISSUE TITLE
Enhance CSS Styling and Improve Aesthetics of the webpage

### ISSUE THREAD

**Issue by AnkitLuhar512117** [sristy17/MindDrive#7]
The current button styling and alignments are not in proper proportion, leading to an unappealing design. We need to adjust these styles to improve visual consistency and aesthetics.

##Button Styling:

1>Fix the size and alignment of buttons to maintain a proper ratio.
2>Ensure buttons are uniformly styled across the webpage.

##Button Effects:

1>Add hover effects and transitions to buttons for better interactivity.
2>Ensure smooth animations without affecting performance.

##styling of the components:
1>adjusting in the proper manner to achieve the aestheic look of website.

here is the screenshot:
![Screenshot (925)](https://github.com/user-attachments/assets/aec5ca25-79dd-4e2c-82f9-adbbe0ec7c02)
![Screenshot (927)](https://github.com/user-attachments/assets/68d1a2ba-e95a-4761-a30e-d47498988c4e)

**Assign this issue under the Hacktoberfest2024.**

**Comment by AnkitLuhar512117** [comment]
@sristy17 kindly assign the issue under the hacktoberfest

**Comment by sristy17** [comment]
Go ahead! @AnkitLuhar
