### ISSUE TITLE
[BUG] Loading BG in Darkmode

### ISSUE THREAD

**Issue by pooranjoyb** [sristy17/MindDrive#72]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

There's a white background which is visible in darkmode when the screen loads. We need to make it transparent. 

### Screenshots

![image](https://github.com/user-attachments/assets/aa14c168-4424-40d2-a072-f7acb112d125)

### Do you want to work on this issue?

No

**Comment by AliHassan245** [comment]
Kindly give me this issue. I can work on it.

**Comment by sristy17** [comment]
> Kindly give me this issue. I can work on it.

done.

**Comment by pooranjoyb** [comment]
Update? @AliHassan245

**Comment by AliHassan245** [comment]
Hopefully I will update you with my progress after weekend

**Comment by AliHassan245** [comment]
Kindly see is this feature you want.
![bug 1 0](https://github.com/user-attachments/assets/16b5affa-48d6-4466-a67f-6b122a1918bf)
![bug 1 1](https://github.com/user-attachments/assets/f52090b1-db4f-4164-8881-0c8b669143e0)

**Comment by sristy17** [comment]
> Kindly see is this feature you want.
> ![bug 1 0](https://github.com/user-attachments/assets/16b5affa-48d6-4466-a67f-6b122a1918bf)
> ![bug 1 1](https://github.com/user-attachments/assets/f52090b1-db4f-4164-8881-0c8b669143e0)
> 
> 

Make this theme based

**Comment by AliHassan245** [comment]
@sristy17 @pooranjoyb  I’ve implemented a theme-based UI for the modal box, but I’m encountering issues with it not applying correctly. If I generate a pull request with the changes, would you be able to take a look and assist in resolving the issue? Your expertise would be invaluable in helping the theme work smoothly.

**Comment by sristy17** [comment]
> @sristy17 @pooranjoyb  I’ve implemented a theme-based UI for the modal box, but I’m encountering issues with it not applying correctly. If I generate a pull request with the changes, would you be able to take a look and assist in resolving the issue? Your expertise would be invaluable in helping the theme work smoothly. 
> 

Ok will check and get back to you

**Comment by AliHassan245** [comment]
@sristy17 @pooranjoyb Secondly I also want to discuss something with you.

**Comment by AliHassan245** [comment]
I wanted to let you know that my second-year end semester exams at NUST are approaching, from December 30 to January 10. While I truly wish I could contribute more, due to my exam schedule, I regret that I can only submit two pull requests for MindDrive AI under KWoC. I hope you understand, and I truly appreciate your support during this time.

**Comment by pooranjoyb** [comment]
@AliHassan245 Thanks, we truly appreciate, although we'd suggest that donot limit yourself with event. You are always welcome to contribute to MindDrive :)

**Comment by AliHassan245** [comment]
@pooranjoyb  Thank you so much for your support and understanding. Contributing to MindDrive has been an incredible experience, and I’ve genuinely loved every moment of it! ❤. I’m truly excited about the possibility of contributing more in the future 🚀.

**Comment by AliHassan245** [comment]
@pooranjoyb Bhai Could you kindly share your Instagram? I'd love to connect with you there! ❤

**Comment by pooranjoyb** [comment]
> @pooranjoyb Bhai Could you kindly share your Instagram? I'd love to connect with you there! ❤

You can connect with me in [Linkedin](https://linkedin.com/in/pooranjoyb)
