### ISSUE TITLE
[BUG] White Background pops while loading

### ISSUE THREAD

**Issue by pooranjoyb** [sristy17/MindDrive#73]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

The background needs to be made transparent for the Loading icon. Please fix that.

### Screenshots

![image](https://github.com/user-attachments/assets/5508f76b-755f-4261-8702-4f82b706453f)

### Do you want to work on this issue?

No

**Comment by AliHassan245** [comment]
I want to work on this issue. As far as technical explanation is concerned I need some time if u dont mind hopefully after weekened I will reslove the issue.

**Comment by AliHassan245** [comment]
I want to work on this issue. As far as technical explanation is concerned I need some time if u dont mind hopefully after weekened I will reslove the issue.

**Comment by sristy17** [comment]
> I want to work on this issue. As far as technical explanation is concerned I need some time if u dont mind hopefully after weekened I will reslove the issue.

sure

**Comment by AliHassan245** [comment]
@pooranjoyb @sristy17 Kindly see is this feature you want.
![bug 2 0](https://github.com/user-attachments/assets/7c1365d8-aae9-477f-a8dc-232b75ff88ad)
![bug 2 1](https://github.com/user-attachments/assets/0f21be1a-e274-4ff1-a438-7001335e7a90)

**Comment by sristy17** [comment]
> @pooranjoyb @sristy17 Kindly see is this feature you want. ![bug 2 0](https://private-user-images.githubusercontent.com/141296395/397938964-7c1365d8-aae9-477f-a8dc-232b75ff88ad.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3OTg5MzAsIm5iZiI6MTczNDc5ODYzMCwicGF0aCI6Ii8xNDEyOTYzOTUvMzk3OTM4OTY0LTdjMTM2NWQ4LWFhZTktNDc3Zi1hOGRjLTIzMmI3NWZmODhhZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMVQxNjMwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmEwZjdkOTE3MjE2MTRlOTE1NzUyMzYzMTQ0MzUzYWNkZDA3OGQyNzViNWJiNDRmMGFhYzc1NDEzM2NkZTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ae7_AjEcQS2bmDRdKEJkQEpKC-DSWgEd55sNXDiUrX0) ![bug 2 1](https://private-user-images.githubusercontent.com/141296395/397938972-0f21be1a-e274-4ff1-a438-7001335e7a90.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3OTg5MzAsIm5iZiI6MTczNDc5ODYzMCwicGF0aCI6Ii8xNDEyOTYzOTUvMzk3OTM4OTcyLTBmMjFiZTFhLWUyNzQtNGZmMS1hNDM4LTcwMDEzMzVlN2E5MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMVQxNjMwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTMwODhlMWIzYTE1Y2NiYmRhZmNiZDdlMWMyMDAzMTQ1MjZkMzA1NmViYTNjODM3ZWY2OTE4NTMzOTZjZWIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7sGbWdQ_Lji9Rev4c-6UUWvPwKQjnV9XcF_VBlLppV8)

ok

**Comment by pooranjoyb** [comment]
@AliHassan245 LGTM 🚀
