### ISSUE TITLE
[FEATURE] Profile Page for the User

### ISSUE THREAD

**Issue by pooranjoyb** [sristy17/MindDrive#74]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

As of now we don't have a dedicated page for the Profile after the User logs in.

- We have a blank page. displaying the username.
- We need to take in more data as well as show information on the user's Profile Page.

### Proposed Solution

Design the UI for the `Profile Page`

### Current UI 

![image](https://github.com/user-attachments/assets/146f00ed-ce32-48f8-ad40-1c8cb2b2d526)

### Expected UI

![image](https://github.com/user-attachments/assets/5e14fbcd-43aa-415b-86d5-43e854711862)

### Do you want to work on this issue?

No

**Comment by pooranjoyb** [comment]
Use this theme color.


https://coolors.co/palette/ea698b-d55d92-c05299-ac46a1-973aa8-822faf-6d23b6-6411ad-571089-47126b

**Comment by AliHassan245** [comment]
Kindly assign me this issue

**Comment by sristy17** [comment]
> Kindly assign me this issue

u r already assigned with 2 isssues kindly complete them first.

**Comment by AliHassan245** [comment]
ok

**Comment by sristy17** [comment]
@AliHassan245 you can work on this

**Comment by AliHassan245** [comment]
@sristy1I'd love to contribute, but I'm tied up with end-of-semester exams right now. If it were a quick fix, I'd definitely take it on, but this requires more time. I'll be happy to help once exams are over.

**Comment by pooranjoyb** [comment]
Completed in #80
