### ISSUE TITLE
adding the scroll-to-top Button.

### ISSUE THREAD

**Issue by AnkitLuhar512117** [sristy17/MindDrive#8]
**Implement a scroll-to-top button to improve user navigation, allowing users to quickly return to the top of the page.**

**##Scroll-to-Top Button Implementation:**

1>Add a button that appears when the user scrolls down the page.
2>Clicking the button smoothly scrolls the user back to the top.

**##Styling:**

1>Ensure the button is visually distinct but unobtrusive.
2>Add a hover effect to enhance user interaction.
 here is the screenshot::
![Screenshot (926)](https://github.com/user-attachments/assets/e45e67b0-8fad-41dc-b6d2-3a1b7e59f915)

Assign this issue under the HacktoberFest2024.

**Comment by AnkitLuhar512117** [comment]
@sristy17 kindly assign the issue under the hacktoberfest

**Comment by sristy17** [comment]
Go for it! @AnkitLuhar

**Comment by Swayam-hue** [comment]
Assign me this issue.

**Comment by sristy17** [comment]
@AnkitLuhar If possible create a PR by tomorrow or else will assign to @Swayam-hue

**Comment by manthanmk66** [comment]
Can you assign me this issue.

**Comment by AnkitLuhar512117** [comment]
@sristy17 ,  implementation is already done,due to hactic schedule I forgot to OPEN the PR,can you open the issue again,
